# Generated by Django 5.2.5 on 2025-09-20 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 20, 12, 40, 35, 255520, tzinfo=datetime.timezone.utc), verbose_name='Admission Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('MSCIT', 'MSCIT'), ('KLIC', 'KLIC'), ('CCC', 'CCC'), ('TALLY', 'Tally'), ('MS_OFFICE', 'MS Office'), ('OTHER', 'Other')], default='MSCIT', max_length=50, verbose_name='Course'),
        ),
    ]
