# Generated by Django 5.2.5 on 2025-09-20 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_admission_date_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('mobile_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits', regex='^\\d{10}$')], verbose_name='Mobile Number')),
                ('course', models.CharField(choices=[('MS-CIT', 'MS-CIT'), ('TALLY', 'Tally'), ('ADVANCE_EXCEL', 'Advance Excel'), ('IOT', 'IOT'), ('MOM', 'MOM'), ('SCRATCH', 'Scratch'), ('SARTHI', 'Sarthi')], max_length=50, verbose_name='Course')),
                ('address', models.TextField(verbose_name='Address')),
                ('enquiry_date', models.DateField(auto_now_add=True, verbose_name='Enquiry Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'db_table': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Admission Date'),
        ),
    ]
