# Generated by Django 5.2.5 on 2025-10-03 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enquiry_alter_student_admission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('admission_date', models.DateField(verbose_name='Admission Date')),
                ('course_name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('mobile_own', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits', regex='^\\d{10}$')], verbose_name='Mobile Number (Own)')),
                ('mobile_parents', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits', regex='^\\d{10}$')], verbose_name='Mobile Number (Parents)')),
                ('address', models.TextField(verbose_name='Address')),
                ('qualification', models.CharField(max_length=100, verbose_name='Current Qualification')),
                ('installments', models.CharField(choices=[('1', '1 Installment'), ('2', '2 Installments')], max_length=1, verbose_name='Fee Installments')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='admission_photos/', verbose_name='Student Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'db_table': 'admissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
