# Generated by Django 5.2.5 on 2025-10-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='paid_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paid Fees'),
        ),
        migrations.AddField(
            model_name='admission',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='Total Fees'),
        ),
    ]
